# MOwNiT 
## Laboratorium
## Wybrane zagadnienia algebry liniowej, faktoryzacja
### Algebra liniowa w Julii
https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/


In [1]:
using(LinearAlgebra)

In [2]:
methods(factorize)

# 10 methods for generic function "factorize" from LinearAlgebra:
  [1] factorize(A::Transpose)
     @ C:\Users\kzaja\.julia\juliaup\julia-1.11.3+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LinearAlgebra\src\dense.jl:1494
  [2] factorize(D::Diagonal)
     @ C:\Users\kzaja\.julia\juliaup\julia-1.11.3+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LinearAlgebra\src\diagonal.jl:215
  [3] factorize(A::Tridiagonal)
     @ C:\Users\kzaja\.julia\juliaup\julia-1.11.3+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LinearAlgebra\src\lu.jl:656
  [4] factorize(a::Number)
     @ C:\Users\kzaja\.julia\juliaup\julia-1.11.3+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LinearAlgebra\src\dense.jl:1495
  [5] factorize(A::Adjoint)
     @ C:\Users\kzaja\.julia\juliaup\julia-1.11.3+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LinearAlgebra\src\dense.jl:1493
  [6] factorize(S::SymTridiagonal)
     @ C:\Users\kzaja\.julia\juliaup\julia-1.11.3+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LinearAlgebra\src\ldlt.jl:172
  [7] factorize(A::LinearAlgebra.AbstractTriangular)
     @ C:\Users\kzaja\.julia\juliaup\julia-1.11.3+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LinearAlgebra\src\triangular.jl:2750
  [8] factorize(A::Bidiagonal)
     @ C:\Users\kzaja\.julia\juliaup\julia-1.11.3+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LinearAlgebra\src\bidiag.jl:992
  [9] factorize(A::Union{Hermitian{T, S}, Symmetric{T, S}} where {T, S})
     @ C:\Users\kzaja\.julia\juliaup\julia-1.11.3+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LinearAlgebra\src\symmetric.jl:585
 [10] factorize(A::AbstractMatrix{T}) where T
     @ C:\Users\kzaja\.julia\juliaup\julia-1.11.3+0.x64.w64.mingw32\share\julia\stdlib\v1.11\LinearAlgebra\src\dense.jl:1419

In [3]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Matrix{Int64}:
 1  2  2

In [4]:
y1=[1 ;2 ;3]

3-element Vector{Int64}:
 1
 2
 3

In [5]:
transpose(x1)

3×1 transpose(::Matrix{Int64}) with eltype Int64:
 1
 2
 2

In [6]:
#iloczyn skalarny
dot(x1,y1)

11

 Długość wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [7]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Matrix{Float64}:
 0.141465  0.723435  0.668247
 0.562566  0.310058  0.924866
 0.448429  0.617976  0.955799

In [8]:
#losujemy wektor x
x=rand(3)

3-element Vector{Float64}:
 0.8255250186410245
 0.07630848618738151
 0.8904478291040979

In [9]:
# wyliczamy b
b=A*x

3-element Vector{Float64}:
 0.7670262686880713
 1.3116178534407545
 1.2684355415337618

### Sposoby rozwiązania Ax=b

In [10]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Vector{Float64}:
 0.8255250186410166
 0.07630848618737929
 0.8904478291041045

In [11]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Vector{Float64}:
 0.8255250186410181
 0.07630848618737801
 0.8904478291041029

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1.8/stdlib/LinearAlgebra/#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.8/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


### Faktoryzacja LU

In [12]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0       0.0       0.0
 0.251464  1.0       0.0
 0.797113  0.574506  1.0
U factor:
3×3 Matrix{Float64}:
 0.562566  0.310058   0.924866
 0.0       0.645466   0.435676
 0.0       0.0       -0.031722

In [13]:
# Macierz L
Af.L

3×3 Matrix{Float64}:
 1.0       0.0       0.0
 0.251464  1.0       0.0
 0.797113  0.574506  1.0

In [14]:
#Macierz U
Af.U

3×3 Matrix{Float64}:
 0.562566  0.310058   0.924866
 0.0       0.645466   0.435676
 0.0       0.0       -0.031722

In [15]:
# wektor permulatacji wierszy 
Af.p

3-element Vector{Int64}:
 2
 1
 3

In [16]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A=factorize(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0       0.0       0.0
 0.251464  1.0       0.0
 0.797113  0.574506  1.0
U factor:
3×3 Matrix{Float64}:
 0.562566  0.310058   0.924866
 0.0       0.645466   0.435676
 0.0       0.0       -0.031722

In [17]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Vector{Float64}:
 0.8255250186410181
 0.07630848618737801
 0.8904478291041029

In [18]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Vector{Float64}:
 -8.27097836941527
 -4.820800126118758
  7.2189303136617164

### Faktoryzacja QR


In [19]:
B=rand(10,5)

10×5 Matrix{Float64}:
 0.0258715  0.234971  0.634316     0.98706   0.943027
 0.432404   0.168166  0.586376     0.510919  0.696868
 0.11965    0.719476  0.824378     0.295287  0.719395
 0.378093   0.581734  0.621141     0.638234  0.624301
 0.821174   0.838916  0.000883343  0.313535  0.09646
 0.506404   0.952128  0.138967     0.320935  0.47399
 0.70957    0.740687  0.716651     0.826983  0.895128
 0.634709   0.189462  0.342056     0.91201   0.180884
 0.73128    0.191445  0.625124     0.834745  0.950626
 0.335105   0.439981  0.579827     0.595357  0.114522

In [20]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64, Matrix{Float64}, Vector{Float64}, Vector{Int64}}
Q factor: 10×10 LinearAlgebra.QRPackedQ{Float64, Matrix{Float64}, Vector{Float64}}
R factor:
5×5 Matrix{Float64}:
 -2.12087  -1.26234  -1.8139    -1.37618   -1.59467
  0.0       1.33083   0.294291   0.565013   0.219833
  0.0       0.0      -0.943457   0.224632  -0.487947
  0.0       0.0       0.0       -0.752015   0.209487
  0.0       0.0       0.0        0.0        0.561451
permutation:
5-element Vector{Int64}:
 4
 2
 5
 1
 3

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

### Zastosowanie faktoryzacji do metody najmniejszych kwadratów

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znaleźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

#### 1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [21]:
A=zeros(6,3) 

6×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [22]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Vector{Int64}:
 1
 2
 4
 4
 3
 0

In [23]:
A[:,1]=x.^2

6-element Vector{Int64}:
  1
  4
  9
 16
 25
 36

In [24]:
A[:,2]=x

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [25]:
A[:,3]=ones(6)

6-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [26]:
A

6×3 Matrix{Float64}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

#### 2. Dokonujemy faktoryzacji QR macierzy A 

In [27]:
 AF=factorize(A)

QRPivoted{Float64, Matrix{Float64}, Vector{Float64}, Vector{Int64}}
Q factor: 6×6 LinearAlgebra.QRPackedQ{Float64, Matrix{Float64}, Vector{Float64}}
R factor:
3×3 Matrix{Float64}:
 -47.697  -9.24587  -1.90788
   0.0    -2.34816  -1.43091
   0.0     0.0       0.559017
permutation:
3-element Vector{Int64}:
 1
 2
 3

In [28]:
Q=Matrix(AF.Q)

6×3 Matrix{Float64}:
 -0.0209657  -0.343313    0.838525
 -0.0838628  -0.521522    0.167705
 -0.188691   -0.534625   -0.223607
 -0.335451   -0.382624   -0.33541
 -0.524142   -0.0655178  -0.167705
 -0.754765    0.416693    0.279508

In [29]:
# można przetestować ortogonalność:
Transpose(Q)*Q

3×3 Matrix{Float64}:
 1.0           5.43927e-17   2.97814e-17
 5.43927e-17   1.0          -7.18715e-17
 2.97814e-17  -7.18715e-17   1.0

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [30]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(Q)*y)[1:3])

3-element Vector{Float64}:
 -0.5714285714285724
  3.94285714285715
 -2.8000000000000145

Więcej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [31]:
A \ y

3-element Vector{Float64}:
 -0.571428571428572
  3.942857142857148
 -2.8000000000000136

In [32]:
#sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
fit(x,y, 2)

Polynomial(-2.8000000000000136 + 3.942857142857148*x - 0.571428571428572*x^2)

In [33]:
@which fit

Polynomials

### Zadania

#### Zadanie 1 (1pkt)
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x.
Nastepnie rozwiąż równanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

#### Zadanie 2 (1pkt)
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda z użyciem faktoryzacji QR zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

#### Zadanie 3 (2 pkt)

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

-   uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

-  zastosowanie faktoryzacji SVD - np. zastosowania w uczeniu maszynowym 

