# MOwNiT 
## Laboratorium
## Wybrane zagadnienia algebry liniowej, faktoryzacja
### Algebra liniowa w Julii
https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/index.html

In [1]:
using(LinearAlgebra)

In [2]:
methods(factorize)

# 11 methods for generic function "factorize":
[1] factorize(A::StridedArray{T, 2}) where T in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1207
[2] factorize(A::Adjoint) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1283
[3] factorize(A::Transpose) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1284
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\triangular.jl:2676
[5] factorize(A::Union{Hermitian{Complex{Float64},var"#s828"}, Hermitian{Float64,var"#s828"}, Symmetric{Float64,var"#s828"}} where var"#s828"<:SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:1538
[6] factorize(A::Union{Hermitian{T,S}, Symmetric{T,S}} where S where T) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\symmetric.jl:634
[7] factorize(A::Tridiagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\lu.jl:555
[8] factorize(D::Diagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\diagonal.jl:121
[9] factorize(A::Bidiagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\bidiag.jl:875
[10] factorize(S::SymTridiagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\ldlt.jl:166
[11] factorize(A::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\kzaja\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:1508

In [3]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Array{Int64,2}:
 1  2  2

In [4]:
y1=[1 ;2 ;3]

3-element Array{Int64,1}:
 1
 2
 3

In [5]:
transpose(x1)

3×1 Transpose{Int64,Array{Int64,2}}:
 1
 2
 2

In [6]:
#iloczyn skalarny
dot(x1,y1)

11

 Długość wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [7]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Array{Float64,2}:
 0.584445  0.253798  0.193993
 0.552091  0.608555  0.575765
 0.121575  0.655578  0.506962

In [8]:
#losujemy wektor x
x=rand(3)

3-element Array{Float64,1}:
 0.4834167206458264
 0.1399725185634757
 0.8796532122661693

In [9]:
# wyliczamy b
b=A*x

3-element Array{Float64,1}:
 0.4887018814059986
 0.8585445268382984
 0.5964853329860818

### Sposoby rozwiązania Ax=b

In [10]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Array{Float64,1}:
 0.48341672064582636
 0.13997251856347548
 0.8796532122661702

In [11]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Array{Float64,1}:
 0.48341672064582636
 0.13997251856347512
 0.87965321226617

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


### Faktoryzacja LU

In [12]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0      0.0
 0.208019  1.0      0.0
 0.944642  0.61184  1.0
U factor:
3×3 Array{Float64,2}:
 0.584445  0.253798  0.193993
 0.0       0.602783  0.466608
 0.0       0.0       0.107022

In [13]:
# Macierz L
Af.L

3×3 Array{Float64,2}:
 1.0       0.0      0.0
 0.208019  1.0      0.0
 0.944642  0.61184  1.0

In [14]:
#Macierz U
Af.U

3×3 Array{Float64,2}:
 0.584445  0.253798  0.193993
 0.0       0.602783  0.466608
 0.0       0.0       0.107022

In [15]:
# wektor permulatacji 
Af.p

3-element Array{Int64,1}:
 1
 3
 2

In [16]:
# to jest spełnione
Af.L*Af.U==A[Af.p,:]

true

In [17]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0      0.0
 0.208019  1.0      0.0
 0.944642  0.61184  1.0
U factor:
3×3 Array{Float64,2}:
 0.584445  0.253798  0.193993
 0.0       0.602783  0.466608
 0.0       0.0       0.107022

In [18]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Array{Float64,1}:
 0.48341672064582636
 0.13997251856347512
 0.87965321226617

In [19]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Array{Float64,1}:
 -0.18798741919002526
 -0.09711789211026547
  0.8381147792817757

### Faktoryzacja QR


In [20]:
B=rand(10,5)

10×5 Array{Float64,2}:
 0.745821   0.92601    0.881794  0.831205   0.904127
 0.970118   0.748971   0.278336  0.34829    0.887059
 0.265782   0.164165   0.866504  0.403203   0.776582
 0.312464   0.530006   0.70348   0.159994   0.409373
 0.866479   0.668745   0.666256  0.615495   0.0389199
 0.0981493  0.533747   0.584399  0.376981   0.190852
 0.302254   0.497344   0.200622  0.922963   0.510687
 0.0770144  0.0370758  0.591574  0.562747   0.168126
 0.468203   0.769863   0.124682  0.0558474  0.29119
 0.913959   0.0234471  0.457702  0.899056   0.757445

In [21]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.394295    0.267848    0.242774   …  -0.20465    -0.287071    -0.0296948
 -0.512874   -0.334328    0.125087       0.391969   -0.294519    -0.295734
 -0.140512    0.529514   -0.255816      -0.268752    0.368189    -0.427664
 -0.165191    0.374768    0.141328       0.0913286  -0.275485     0.530501
 -0.458083    0.0296521  -0.0197345     -0.179093   -0.00540683  -0.319677
 -0.0518888   0.403361    0.304015   …  -0.1037     -0.0497959    0.226542
 -0.159793   -0.0146408   0.271885      -0.085454    0.0164547   -0.0849263
 -0.0407153   0.42105    -0.191802       0.805653    0.137587    -0.0761873
 -0.247526   -0.168939    0.479086       0.106648    0.760735     0.213795
 -0.483184   -0.161334   -0.637927      -0.115458    0.137717     0.484862
R factor:
5×5 Array{Float64,2}:
 -1.89153  -1.37209  -1.47678   -1.50959   -1.54243
  0.0       1.27232   0.392794   0.618915   0.480285
  0.0  

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

### Zastosowanie faktoryzacji do metody najmniejszych kwadratów

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znaleźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

#### 1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [22]:
A=zeros(6,3) 

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [23]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Array{Int64,1}:
 1
 2
 4
 4
 3
 0

In [24]:
A[:,1]=x.^2

6-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36

In [25]:
A[:,2]=x

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [26]:
A[:,3]=ones(6)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [27]:
A

6×3 Array{Float64,2}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

#### 2. Dokonujemy faktoryzacji QR macierzy A 

In [28]:
 AF=factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Array{Float64,2}:
 -47.697  -9.24587  -1.90788
   0.0    -2.34816  -1.43091
   0.0     0.0       0.559017
permutation:
3-element Array{Int64,1}:
 1
 2
 3

In [29]:
# można przetestować ortogonalność:
Transpose(AF.Q)*AF.Q

6×6 Array{Float64,2}:
  1.0           0.0           2.77556e-17  …   2.77556e-17  -8.32667e-17
  0.0           1.0          -8.32667e-17     -5.55112e-17  -6.93889e-17
  2.77556e-17  -8.32667e-17   1.0             -8.32667e-17   0.0
 -4.16334e-17   2.77556e-17  -8.84709e-17     -9.02056e-17  -3.98986e-17
  2.77556e-17  -5.55112e-17  -8.32667e-17      1.0          -1.38778e-17
 -8.32667e-17  -6.93889e-17   0.0          …  -1.38778e-17   1.0

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [30]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Array{Float64,1}:
 -0.5714285714285723
  3.9428571428571493
 -2.8000000000000136

Więcej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [31]:
A \ y

3-element Array{Float64,1}:
 -0.5714285714285723
  3.9428571428571493
 -2.8000000000000136

In [33]:
#sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
fit(x,y, 2)

Polynomial(-2.800000000000001 + 3.942857142857141*x - 0.5714285714285708*x^2)

Funkcja <a href="https://github.com/JuliaMath/Polynomials.jl/blob/ef129b779d08f791eb607e390ca9d31d8c08ead1/src/Polynomials.jl#L689-L707">
polyfit</a> 

TODO używa własnie tej metody (polyfit zmienilo sie na fit - sprawdzic to)


### Zadania

#### Zadanie 1 
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x.
Nastepnie rozwiąż równanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

#### Zadanie 2
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

#### Zadanie 3

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

-   uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

-  zastosowanie faktoryzacji SVD - przykład zastosowania w uczeniu maszynowym https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254


